### ISSUE TITLE
request for update of conda forge version

### ISSUE THREAD

**Issue by shimwell** [RemiTheWarrior/plasma-boundaries#26]
I am investigating [some package conflicts](https://github.com/fusion-energy/paramak/runs/5218785699?check_suite_focus=true) and would like to rule out this package as a source of those conflicts

@RemDelaporteMathurin would you be able to consider merging in the conda-forge updates updates
https://github.com/conda-forge/plasmaboundaries-feedstock/pulls

The recipe maintainer name is your old username so I guess this could be update at the same time
https://github.com/conda-forge/plasmaboundaries-feedstock/blob/4d1774e53bcbc0e97b6fe756738066617084dbc8/recipe/meta.yaml#L50

**Comment by RemDelaporteMathurin** [comment]
i merged the first but the second has conflicts... 
I don't really know what I doing there as I am not a conda user

**Comment by RemDelaporteMathurin** [comment]
does that sound familiar to you?
https://github.com/conda-forge/plasmaboundaries-feedstock/pull/3/conflicts

**Comment by shimwell** [comment]
https://github.com/conda-forge/plasmaboundaries-feedstock/pull/3#issuecomment-836834307

Your user name might be the issue

**Comment by shimwell** [comment]
your link

> does that sound familiar to you? https://github.com/conda-forge/plasmaboundaries-feedstock/pull/3/conflicts

this link does not work for me

**Comment by shimwell** [comment]
updating conda distribution on fusion-energy channel instead as access to conda-forge is locked to old username I don't have access to

https://anaconda.org/fusion-energy/plasma_boundaries
