### ISSUE TITLE
update of setup.py

### ISSUE THREAD

**Issue by shimwell** [RemiTheWarrior/plasma-boundaries#27]
@RemDelaporteMathurin  shall we update this setup.py in the way @LiamPattinson from PlasmaFair taught us.

We can replace most of the setup.py with a setup.cfg and pyproject.toml

Shall I make a PR for this?

**Comment by RemDelaporteMathurin** [comment]
Sure!

**Comment by shimwell** [comment]
There are a few related things that could do with a tidy up like the github action as well if that is ok

**Comment by shimwell** [comment]
solved
